<!-- Book Events Form Page -->
<!-- Developed By Michael Stringer  -->

<!-- PHP to start a session and set the directory for the data to be saved -->
<?php
    ini_set("session.save_path", "/home/unn_w18019818/sessionData");
    session_start();
?>

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>North Events</title>
    <link rel="stylesheet" type="text/css" href="stylesheet.css" >
</head>
<body>
    <header> 
        
    </header>
                <!-- The Navigation Bar -->
                <nav>
                <a href="index.php" class='navBtns'> Home </a>
                <a href="events.php" class='navBtns'> Events </a>
                <a href="bookEventsForm.php" class='navBtns'> Book Events </a>
                <a href="credits.php" class='navBtns'> Credits </a>
                
<!-- PHP SCRIPT STARTS HERE -->
<?php
//If the session is logged in then display the logout button else display the login button
    if(isset($_SESSION["logged-in"]))
    {
        echo "<a href='logoutProcess.php' class='navBtns'> Logout </a>";
    }
    else
    {
        echo "<a id='loginBtn' class='navBtns'> Login </a>";
    }
?> 
    </nav> 
    
<?php
/* This code dynamically generates a web page containing a form designed with the html required to display one
checkbox for each of the records currently held in the nmc_records database table has been provided for you in the
assessment section for the module on blackboard. The user can select one or more records that they are interested in
ordering by clicking the checkboxes.
Use the browser to look at the structure of the html generated by the php code. */

$url = "http://unn-izge1.newnumyspace.co.uk/KF5002/assessment/bookEventsFormInc.php";
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
$result = curl_exec($curl);
curl_close($curl);
echo $result;
?>

<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for the assignment -->
    <script src="eventBookingScripts.js"> </script>
    
     <!-- Popup box for login are stored here. These are hidden by default only being displayed when a login button is pressed --!>
        
           <!-- The Login Box -->
<div id="login" class="login">

  <!-- Login Box Content -->
  <div class="loginContent">
    <div class="loginHeader">
      <span class="close">&times;</span>
      <h2>Login</h2>
    </div>
      
        <!-- Form that contains the input boxes for username and password that will pass them over to the loginProcess.php to be checked when the user clicks the login button -->
        <form method="post" action="loginProcess.php">
        
            Username: <input name="username" type="text"> <br>
            Password: <input type="password" name="password"> <br>
            <input type="submit" value="Login"> 
            
        
        
        </form>
           
    
  </div>
</div>     
        <script type="text/javascript" src="loginForm.js"> </script> <!-- login form script -->
        
</body>
</html>